### ISSUE TITLE
How to add token ?

### ISSUE THREAD

**Issue by joibor** [funivan/github-autopr#14]
Hi, 

Thanks for this package, but I have question where can I put the GITHUB_TOKEN ? 

In my nodejs.yml crash when added secrets...

Thanks in advance

**Comment by funivan** [comment]
Hello. 
At that moment this action is not supported in the new "Github action" system (with yaml syntax). I will try to convert it as soon as possible.

https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

**Comment by funivan** [comment]
I have released version 0.2.0 with new yaml format support.

For example my job configuration:
```yaml
on: push
name: Fast prototype
jobs:
  createPR:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: funivan/github-autopr@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: .head_commit.message .*#pr.*
```

Github action will automatically create a Pull request for commits with `#pr` hashtag in the commit message.

`GITHUB_TOKEN` is available for all actions by default, you can read more https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret

Please let me know if you have any questions.
